name: apk 빌드

on:
  push:
    branches: [master, dev]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build APK
        run: bash ./gradlew assembleRelease --stacktrace

      - name: 파일 리스트 디버깅
        run: |
          apt-get update && apt-get install -y tree
          tree

      - name: 슬랙에 업로드
        uses: rtCamp/action-slack-notify@master
        env:
          SLACK_CHANNEL: android-build
          SLACK_COLOR: '#DD0000'
          SLACK_MESSAGE: ${{ github.event.head_commit.message }}
          SLACK_TITLE: '새로운 안드로이드 APK가 빌드되었습니다.'
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      - uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACKBOT_TOKEN }}
          channels: ${{ secrets.SLACKBOT_CHANNELS }}
          file_path: 'app/build/outputs/apk/release/app-release-unsigned.apk'
          file_name: 'app-release-unsigned.apk'
          file_type: 'apk'
          initial_comment: ${{ github.event.head_commit.message }}