name: apk 빌드

on:
  push:
    branches: [master, dev]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: make app dir
        run: mkdir app
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: app
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ANDROID_ALIAS }}
          keyStorePassword: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.ANDROID_KEY_PASSWORD }}
      #      env:
      #        // override default build-tools version (29.0.3) -- optional
      #        BUILD_TOOLS_VERSION: "30.0.2"
      - name: 파일 리스트 디버깅
        run: |
          apt-get update && apt-get install -y tree
          tree

      - name: 슬랙에 APK 업로드
        uses: MeilCli/slack-upload-file@v1
        with:
          slack_token: ${{ secrets.SLACKBOT_TOKEN }}
          channels: khumu
          file_path: 'app/app-release.apk'
          file_name: 'app-release.apk'
          file_type: 'apk'
          initial_comment: '새로운 안드로이드 APK가 빌드되었습니다 - ${{ github.event.head_commit.message }}'